// <auto-generated />
using System;
using HealthCare;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthCare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthcareAPI.Models.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookedByPatientId")
                        .HasColumnType("integer");

                    b.Property<int>("CaregiverId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookedByPatientId");

                    b.HasIndex("CaregiverId");

                    b.ToTable("AppointmentSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaregiverId = 1,
                            EndTime = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            StartTime = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CaregiverId = 1,
                            EndTime = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            StartTime = new DateTime(2026, 6, 1, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CaregiverId = 2,
                            EndTime = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            IsBooked = false,
                            StartTime = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HealthcareAPI.Models.Caregiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Caregivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dr. Anna Andersson",
                            Specialty = "Allmänmedicin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dr. Björn Berg",
                            Specialty = "Kardiologi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dr. Cecilia Carlsson",
                            Specialty = "Dermatologi"
                        });
                });

            modelBuilder.Entity("HealthcareAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthcareAPI.Models.AppointmentSlot", b =>
                {
                    b.HasOne("HealthcareAPI.Models.Patient", "BookedByPatient")
                        .WithMany("BookedSlots")
                        .HasForeignKey("BookedByPatientId");

                    b.HasOne("HealthcareAPI.Models.Caregiver", "Caregiver")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedByPatient");

                    b.Navigation("Caregiver");
                });

            modelBuilder.Entity("HealthcareAPI.Models.Caregiver", b =>
                {
                    b.Navigation("AppointmentSlots");
                });

            modelBuilder.Entity("HealthcareAPI.Models.Patient", b =>
                {
                    b.Navigation("BookedSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
